[id]
version = 1.0.0
name = openai_compliance_addon_for_splunk

[install]
is_configured = false
state = enabled
build = 1

[launcher]
author = FDSE
version = 1.0.0
description = This add-on ingests data from an enterprise ChatGPT workspace using the OpenAI Compliance API.

[package]
id = openai_compliance_addon_for_splunk

[ui]
label = OpenAI Compliance Add-on for Splunk
supported_themes = light, dark
is_visible = true

[triggers]
reload.openai_compliance_addon_for_splunk_settings = simple
reload.openai_compliance_addon_for_splunk_account = simple